apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-deployment
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-sample-app
  template:
    metadata:
      labels:
        app: dotnet-sample-app
    spec:
      containers:
        - name: dotnet-sample-app
          image: devopscontainerreg.azurecr.io/dotnet-sample-project:ci-pipeline-66
          ports:
            - containerPort: 80

        - name: mssql
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: "P4ssW0rd!"
          volumeMounts:
            - name: database-storage
              mountPath: /var/opt/mssql

      volumes:
        - name: database-storage
          emptyDir: {}