apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-deployment
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-sample-app
  template:
    metadata:
      labels:
        app: dotnet-sample-app
    spec:
      containers:
        - name: dotnet-sample-app
          image: devopscontainerreg.azurecr.io/dotnet-sample-project:ci-pipeline-66
          ports:
            - containerPort: 80
          env:
            - name: SigningKey
              value: 58a97cd766d741e8a21b8d3c4279652469801dc8da844fa5bf80afeea85aa472
            - name: ConnectionStrings__Context
              value: Server=localhost:1433;Database=Database;User Id=sa;Password=P4ssW0rd!;TrustServerCertificate=true;
            - name: Serilog__WriteTo__1__Args__path
              value: /app/logs/

        - name: mssql
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: "P4ssW0rd!"
          volumeMounts:
            - name: database-storage
              mountPath: /var/opt/mssql

      volumes:
        - name: database-storage
          emptyDir: {}