# Test Pipeline
trigger:
  branches:
    include:
      - main
      - feature/*

pool:
  name: AzureVM

variables:
  dockerRegistryServiceConnection: 'devops-service-connection'
  imageRepository: 'dotnet-sample-project'
  tag: '$(Build.SourceBranchName)-$(Build.BuildId)'

stages:
- stage: Build
  displayName: 'Docker Build'
  jobs:
  - job: docker_build
    displayName: 'Build image'
    steps:
    - task: Docker@2
      displayName: 'Build image'
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'build'
        Dockerfile: 'dotnet-sample-project/Dockerfile'
        tags: '$(tag)'

- stage: Push
  displayName: 'Push image to ACR'
  jobs:
  - job: docker_push
    displayName: 'Push image'
    steps:
    - task: Docker@2
      displayName: 'Push image'
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'push'
        tags: '$(tag)'